name: Main Push Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up Python 3.9.5
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.5'
      -
        run:
          pip install -r requirements.txt
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: flask
      -
        name: Run
        run:
          docker run -d -p 5000:5000 flask
          python3 -m unittest test.py
