name: Main Push Test 2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up Python 3.9.5
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.5'
      -
        run:
          pip install -r requirements.txt
      -
        run:
          python -m unittest test2.py          
